---

- name: Install ansible libraries
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - ansible
    - ca-certificates
    # Libraries (ansible)
    - python-pycurl
    - python-mysqldb
    - python-passlib
    - python-netaddr
