---

- name: Install developer compiling packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - build-essential
    - closure-compiler
    - g++

- name: Install dev packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - libsqlite3-dev
    - php7.0-dev
    - libcurl3-gnutls-dev
    - libxml2-dev
    - libxml2-utils
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
