---

- name: Install developer tool packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - jq
    - sloccount
    - ack-grep
    - tig
    - strace

- name: Install developer status packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - htop
    - atop
    - iftop
    - mytop
    - iotop

- name: Install developer system packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - fuse
    - sshfs
    - xvfb

- name: Install developer network packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - tshark
    - tcpflow
    - tcpdump
    - ngrep
    - swaks
    - ethtool
    - netcat-openbsd
    - mailutils
    - mysql-client

- name: Install developer vcs packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - subversion
    - git
    - git-flow

- name: Install developer other packages
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - dos2unix
    - lynx
    - links

