---

- name: Install nodejs
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - nodejs
    - nodejs-legacy
  
- name: Install npm
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - npm

- name: Install custom npm packages
  npm:
    name:   '{{ item }}'
    global: yes
    state:  latest
    production: yes
  with_items: "{{ PROVISION.npm }}"
  ignore_errors: True
