---

- name: Apply sysctl settings
  command: 'sysctl -p --ignore'

- name: Update grub
  command: 'update-grub'

- name: Restart services for timezone
  command: 'service {{ item }} restart'
  with_items:
    - cron
